apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-service
  description: this is a test component
spec:
  type: service
  lifecycle: production
  owner: guest
  techdocs:
    storageUrl: http://localhost:7007/static/docs
