apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-service
  description: A description of my service
spec:
  type: service
  lifecycle: production
  owner: team-a
  techdocs:
    storageUrl: http://localhost:7007/static/docs
